### PR TITLE
Fix: Vela uses zstd compression function causing OOM (#92)

### PR DESCRIPTION
**Pull request by msun1996**
fix the concurrent number of zstd encoders in k8s container and support zstd configuration re-initialization

### CODE REVIEW

**Comment by charlie0129** [comment]
I think importing `go.uber.org/automaxprocs` should be enough.

**Comment by msun1996** [comment]
> I think importing `go.uber.org/automaxprocs` should be enough.
I can first import `go.uber.org/automaxprocs` to solve the existing problem.
You can consider adding it after configuring the zstd compression concurrency number. I think it may have an impact on large batch data processing. At the same time, I will verify the performance impact of this parameter on our service later.

**Comment by msun1996** [comment]
> I think importing `go.uber.org/automaxprocs` should be enough.

I can first import `go.uber.org/automaxprocs` to solve the existing problem.
You can consider adding it after configuring the zstd compression concurrency number. I think it may have an impact on large batch data processing. At the same time, I will verify the performance impact of this parameter on our service later.

**Review by charlie0129 — APPROVED** [review]
LGTM

**Pull request merged**
